/**
 * Initializes level 1 with the specified entities.
 */
function initLevel1() {
  level1 = new Level(
    // Array of enemies
    [
      new Golem(),
      new Golem(),
      new Golem(),
      new Golem(),
      new Golem(),
      new Golem(),
      new Golem(),
      new Golem(),
      new Golem(),
      new Golem(),
      new Golem2(),
      new Golem2(),
      new Golem2(),
      new Golem3(),
      new Golem3(),
      new Golem3(),
      new Golem3(),
      new Golem3(),
      new Golem3(),
      new Golem3(),
      new Golem3(),
      new Endboss(),
    ],
    // Array of clouds
    [
      new Cloud("img/clouds/PNG/Clouds_white/Shape2/cloud_shape2_1.png"),
      new Cloud("img/clouds/PNG/Clouds_white/Shape2/cloud_shape2_2.png"),
      new Cloud("img/clouds/PNG/Clouds_white/Shape2/cloud_shape2_3.png"),
      new Cloud("img/clouds/PNG/Clouds_white/Shape2/cloud_shape2_4.png"),

      new Cloud("img/clouds/PNG/Clouds_white/Shape2/cloud_shape2_1.png"),
      new Cloud("img/clouds/PNG/Clouds_white/Shape2/cloud_shape2_2.png"),
      new Cloud("img/clouds/PNG/Clouds_white/Shape2/cloud_shape2_3.png"),
      new Cloud("img/clouds/PNG/Clouds_white/Shape2/cloud_shape2_4.png"),
    ],
    // Array of fire items
    [
      new FireItem("img/items/firePotion.png"),
      new FireItem("img/items/firePotion.png"),
      new FireItem("img/items/firePotion.png"),
      new FireItem("img/items/firePotion.png"),
      new FireItem("img/items/firePotion.png"),
      new FireItem("img/items/firePotion.png"),
      new FireItem("img/items/firePotion.png"),
      new FireItem("img/items/firePotion.png"),
      new FireItem("img/items/firePotion.png"),
      new FireItem("img/items/firePotion.png"),
      new FireItem("img/items/firePotion.png"),
      new FireItem("img/items/firePotion.png"),
      new FireItem("img/items/firePotion.png"),
      new FireItem("img/items/firePotion.png"),
      new FireItem("img/items/firePotion.png"),
      new FireItem("img/items/firePotion.png"),
      new FireItem("img/items/firePotion.png"),
      new FireItem("img/items/firePotion.png"),
      new FireItem("img/items/firePotion.png"),
      new FireItem("img/items/firePotion.png"),
      new FireItem("img/items/firePotion.png"),
      new FireItem("img/items/firePotion.png"),
      new FireItem("img/items/firePotion.png"),
      new FireItem("img/items/firePotion.png"),
      new FireItem("img/items/firePotion.png"),
      new FireItem("img/items/firePotion.png"),
      new FireItem("img/items/firePotion.png"),
      new FireItem("img/items/firePotion.png"),
      new FireItem("img/items/firePotion.png"),
      new FireItem("img/items/firePotion.png"),
      new FireItem("img/items/firePotion.png"),
      new FireItem("img/items/firePotion.png"),
      new FireItem("img/items/firePotion.png"),
      new FireItem("img/items/firePotion.png"),
      new FireItem("img/items/firePotion.png"),
      new FireItem("img/items/firePotion.png"),
      new FireItem("img/items/firePotion.png"),
      new FireItem("img/items/firePotion.png"),
      new FireItem("img/items/firePotion.png"),
      new FireItem("img/items/firePotion.png"),
    ],
    // Array of background objects
    [
      new BackgroundObject("img/game_background_4/layers2/battleground.png", -719),
      new BackgroundObject("img/game_background_4/layers2/back_land.png", -719),
      new BackgroundObject("img/game_background_4/layers2/back_decor.png", -719),
      new BackgroundObject("img/game_background_4/layers2/ground_decor.png", -719),
      new BackgroundObject("img/game_background_4/layers2/front_decor.png", -719),
      new BackgroundObject("img/game_background_4/layers/battleground.png", 0),
      new BackgroundObject("img/game_background_4/layers/back_land.png", 0),
      new BackgroundObject("img/game_background_4/layers/back_decor.png", 0),
      new BackgroundObject("img/game_background_4/layers/ground_decor.png", 0),
      new BackgroundObject("img/game_background_4/layers/front_decor.png", 0),
      new BackgroundObject("img/game_background_4/layers2/battleground.png", 719),
      new BackgroundObject("img/game_background_4/layers2/back_land.png", 719),
      new BackgroundObject("img/game_background_4/layers2/back_decor.png", 719),
      new BackgroundObject("img/game_background_4/layers2/ground_decor.png", 719),
      new BackgroundObject("img/game_background_4/layers2/front_decor.png", 719),

      new BackgroundObject("img/game_background_4/layers/battleground.png", 719 * 2),
      new BackgroundObject("img/game_background_4/layers/back_land.png", 719 * 2),
      new BackgroundObject("img/game_background_4/layers/back_decor.png", 719 * 2),
      new BackgroundObject("img/game_background_4/layers/ground_decor.png", 719 * 2),
      new BackgroundObject("img/game_background_4/layers/front_decor.png", 719 * 2),
      new BackgroundObject("img/game_background_4/layers2/battleground.png", 719 * 3),
      new BackgroundObject("img/game_background_4/layers2/back_land.png", 719 * 3),
      new BackgroundObject("img/game_background_4/layers2/back_decor.png", 719 * 3),
      new BackgroundObject("img/game_background_4/layers2/ground_decor.png", 719 * 3),
      new BackgroundObject("img/game_background_4/layers2/front_decor.png", 719 * 3),
    ]
  );
}
